# Generated by Django 3.2 on 2021-05-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='remark',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='file',
            name='UserID',
            field=models.IntegerField(default=0),
        ),
    ]
