# Generated by Django 3.2.5 on 2021-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20210503_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Text',
            field=models.CharField(default='abdo', max_length=20),
            preserve_default=False,
        ),
    ]
