# Generated by Django 3.2.5 on 2021-07-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_file_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='UserID',
        ),
        migrations.AddField(
            model_name='file',
            name='FileName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='UserName',
            field=models.CharField(default='abdo', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='Text',
            field=models.CharField(max_length=500),
        ),
    ]
